# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'idap_study_task10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for idap_study_task10

pod 'SnapKit'
pod 'SwiftGen'
pod 'MTCircularSlider', :git => 'https://github.com/filippkos/MTCircularSlider', :commit => '4310d40'
pod 'lottie-ios'

end
