# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'idap_study_task10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for idap_study_task10

pod 'SnapKit'
pod 'SwiftGen'
pod 'RxSwift'
pod 'RxCocoa'
pod 'MTCircularSlider', :git => 'https://github.com/filippkos/MTCircularSlider', :commit => 'edad59e'
pod 'UIImageColors', :git => 'https://github.com/filippkos/UIImageColors', :commit => 'c13e92c'
pod 'lottie-ios'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
      end
    end
  end


end
