# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'idap_study_task9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for idap_study_task9

pod 'SnapKit'

end
